### ISSUE TITLE
大佬，刺猬猫签到好像不行了

### ISSUE THREAD

**Issue by zhenghan123** [xingluo233/qiandao#4]
file:///home/runner/work/qiandao/qiandao/src/scripts/ciweimao.js:227
    let a = res.daily_task_list[2].task_type;
                ^
TypeError: Cannot read properties of undefined (reading 'daily_task_list')
    at ce (file:///home/runner/work/qiandao/qiandao/src/scripts/ciweimao.js:227:[17](https://github.com/zhenghan123/qiandao/actions/runs/10087291902/job/27891215863#step:5:18))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.main (file:///home/runner/work/qiandao/qiandao/src/scripts/ciweimao.js:254:5)
    at async main (file:///home/runner/work/qiandao/qiandao/src/index.js:63:28)
    at async file:///home/runner/work/qiandao/qiandao/src/index.js:105:1
Node.js v[21](https://github.com/zhenghan123/qiandao/actions/runs/10087291902/job/27891215863#step:5:22).2.0

**Comment by zhenghan123** [comment]
辛苦大佬了
